[profile.default]
src = "src"
out = "out"
libs = ["lib"]
via_ir = true
optimizer_runs = 200

[profile.default.rpc_endpoints]
mainnet = "https://eth-mainnet.g.alchemy.com/v2/${ALCHEMY_KEY}"

[profile.default.fmt]
wrap_comments = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
