name: test

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main

env:
  FOUNDRY_PROFILE: ci

jobs:
  check:
    strategy:
      fail-fast: true

    name: Foundry project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          submodules: recursive

      - name: Install Foundry
        uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1.9.1
        with:
          version: nightly

      - name: Run Forge build
        run: |
          forge --version
          forge build --sizes --skip Import
        id: build

      - name: Check foundry.lock matches submodule pins
        run: forge build --locked

      - name: Run Forge tests
        run: |
          forge test -vvv
        id: test
